### ISSUE TITLE
Cannot compile bitcalc

### ISSUE THREAD

**Issue by olm52** [OpenEneaLinux/rt-tools#5]
I  have this error compiling bit calc. Archlinux updated to today, with gcc 8.2.1+20181127-1 and cmake 3.13.2-1

[audiolinux@archlinux bitcalc]$ make
Scanning dependencies of target bitcalc
[ 11%] Building C object src/CMakeFiles/bitcalc.dir/bitcalc.c.o
/home/audiolinux/Downloads/Temp/rt-tools/bitcalc/src/bitcalc.c: In function ‘main’:
/home/audiolinux/Downloads/Temp/rt-tools/bitcalc/src/bitcalc.c:438:4: error: this statement may fall through [-Werror=implicit-fallthrough=]
    usage();
    ^~~~~~~
/home/audiolinux/Downloads/Temp/rt-tools/bitcalc/src/bitcalc.c:439:3: note: here
   case 'V':
   ^~~~
/home/audiolinux/Downloads/Temp/rt-tools/bitcalc/src/bitcalc.c:440:4: error: this statement may fall through [-Werror=implicit-fallthrough=]
    version();
    ^~~~~~~~~
/home/audiolinux/Downloads/Temp/rt-tools/bitcalc/src/bitcalc.c:441:3: note: here
   case 'v':
   ^~~~
/home/audiolinux/Downloads/Temp/rt-tools/bitcalc/src/bitcalc.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-aggressive-loop-optimization’ [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/bitcalc.dir/build.make:63: src/CMakeFiles/bitcalc.dir/bitcalc.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/bitcalc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by matslil** [comment]
Could you try adding
/* NOTREACHED /*
after the "usage()" and "version()" lines and see if the compiler understands that. It is really a lint comment, but with some luck the compiler might understand it.

If this does not work it might require a change that will depend on compiler/C version.

**Comment by olm52** [comment]
No, unfortunately this is not working.

**Comment by matslil** [comment]
Pity, then some attribute will be needed, and the syntax for that will depend on compiler and compiler version. You could do some experiments on your side, it will unfortunately take some time before I will have the time to do some experiments myself.

**Comment by matslil** [comment]
I have now pushed a fix, could you try and see if it works for you?
